### ISSUE TITLE
canonical coordinates maps for background

### ISSUE THREAD

**Issue by thucz** [wyysf-98/SweetDreamer#2]
How do you handle the background when estimating the canonical coordinates maps? As the background is empty, how do you estimate their canonical coordinates?

**Comment by wyysf-98** [comment]
Hello, the background is randomly set to a value between 0 and 1. 

More specifically, during the finetuning process of the UNet on the 64 x 64 x 4 latent space, the input consists of the CMM (64 x 64 x 3, which is blended using alpha blending with the random background) and the alpha channel (64 x 64 x 1). We will provide additional details about this process in the paper to clarify it further. 

Hope this helps :)

**Comment by thucz** [comment]
thanks!
